# Configuration for arr-trailer-core

# --- Global Settings ---
log_level: "info" # "info" or "debug"
dry_run: false # if true, no changes will be made (e.g., no downloads)

# Optional: Provide a TMDB API key for higher quality trailer searches.
# If this is left empty, a less accurate direct YouTube search will be used as a fallback.
tmdb_api_key: ""

# --- Download settings ---
download:
  enabled: true # Master switch to enable/disable trailer downloading
  yt_dlp_path: "/usr/bin/yt-dlp" # Path to the yt-dlp executable on your server
  # Quality settings for yt-dlp. This is a good default for 1080p.
  quality: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

# --- Instance Configurations ---
radarr:
  - name: "Radarr_1"
    url: "http://localhost:7878"
    api_key: "YOUR_RADARR_API_KEY_HERE"
    path_mappings:
      - from: "/movies" #'from' path in Docker
        to: "/mnt/user/media/movies" # 'to' path in host system
  # Uncomment the following block to add another Radarr instance, add as many you want, just copy the block and change the name, url, api_key, and path_mappings
  # - name: "Radarr_2"
  #   url: "http://localhost:7878"
  #   api_key: "YOUR_RADARR_2_API_KEY_HERE"
  #   path_mappings:
  #     - from: "/movies" #'from' path in Docker
  #       to: "/mnt/user/media/movies4k" # 'to' path in host system

sonarr:
  - name: "Sonarr_1"
    url: "http://localhost:8989"
    api_key: "YOUR_SONARR_API_KEY_HERE"
    path_mappings:
      - from: "/tv" #'from' path in Docker
        to: "/mnt/user/media/tv" # 'to' path in host system
  # Uncomment the following block to add another Sonarr instance, add as many you want, just copy the block and change the name, url, api_key, and path_mappings
  # - name: "Sonarr_2"
  #   url: "http://localhost:8989"
  #   api_key: "YOUR_SONARR_2_API_KEY_HERE"
  #   path_mappings:
  #     - from: "/tv" #'from' path in Docker
  #       to: "/mnt/user/media/anime" # 'to' path in host system