# --- Global Settings ---
log_level: "info" # Log level for console output. Can be "info" or "debug".
dry_run: false # If true, the app will only simulate actions (e.g., no downloads).

# Optional: Provide a TMDB API key for higher quality trailer searches.
# If this is left empty, a less accurate direct YouTube search will be used as a fallback.
tmdb_api_key: ""

# --- Download settings ---
download:
  enabled: true # Enable or disable downloading trailers
  # Path to the yt-dlp executable. Default assumes it's in the same folder.
  yt_dlp_path: "./yt-dlp"
  # Path to the ffmpeg executable. Default assumes it's in the same folder.
  ffmpeg_path: "./ffmpeg"
  # Quality settings for yt-dlp.
  quality: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

# --- Instance Configurations ---
radarr:
  - name: "Radarr_1"
    url: "http://localhost:7878"
    api_key: "YOUR_RADARR_API_KEY_HERE"
    path_mappings:
      - from: "/movies" #'from' path in Docker
        to: "/mnt/user/media/movies" # 'to' path in host system
  # Uncomment the following block to add another Radarr instance, add as many you want, just copy the block and change the name, url, api_key, and path_mappings
  # - name: "Radarr_2"
  #   url: "http://localhost:7878"
  #   api_key: "YOUR_RADARR_2_API_KEY_HERE"
  #   path_mappings:
  #     - from: "/movies" #'from' path in Docker
  #       to: "/mnt/user/media/movies4k" # 'to' path in host system

sonarr:
  - name: "Sonarr_1"
    url: "http://localhost:8989"
    api_key: "YOUR_SONARR_API_KEY_HERE"
    path_mappings:
      - from: "/tv" #'from' path in Docker
        to: "/mnt/user/media/tv" # 'to' path in host system
  # Uncomment the following block to add another Sonarr instance, add as many you want, just copy the block and change the name, url, api_key, and path_mappings
  # - name: "Sonarr_2"
  #   url: "http://localhost:8989"
  #   api_key: "YOUR_SONARR_2_API_KEY_HERE"
  #   path_mappings:
  #     - from: "/tv" #'from' path in Docker
  #       to: "/mnt/user/media/anime" # 'to' path in host system